name: dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Verify formatting
      run: dotnet format --verify-no-changes
    - name: Run tests
      run: dotnet test
    - name: Build
      run: dotnet publish Aoc2022 -r linux-x64  -p:PublishAOT=true -p:AssemblyName=aoc2022 --configuration Release
    - name: Upload the executable as artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: aoc2022
        path: Aoc2022/bin/Release/net7.0/linux-x64/publish/aoc2022
